package:
  name: json-c
  version: 0.11.20130402

source:
  fn: json-c-0.11-20130402.zip
  url: https://github.com/json-c/json-c/archive/json-c-0.11-20130402.zip

build:
  number: 0

about:
  home: http://github.com/json-c/json-c
  license: GPL?
