package:
  name: json-c
  version: 0.12.20140410

source:
  git: https://github.com/json-c/json-c.git
  git_rev:  537f8bcbdbdc10ffa7673199a0be82ca4eb56ec8

build:
  number: 0

about:
  home: http://github.com/json-c/json-c
  license: GPL?
