package:
  name: json-c
  version: 0.12.20140410

source:
  fn: json-c-0.12-20140410.tar.gz
  url: https://github.com/json-c/json-c/archive/json-c-0.12-20140410.tar.gz  

build:
  number: 0

about:
  home: http://github.com/json-c/json-c
  license: GPL?
